basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for managing shortcuts.
  termsOfService: http://swagger.io/terms/
  title: Multy API
  version: "1.0"
paths:
  /dofus-check/start:
    post:
      description: Starts the DofusCheckService which monitors the Dofus window state
      responses:
        "200":
          description: DofusCheck service started successfully
          schema:
            type: string
        "500":
          description: Error occurred while starting the service
          schema:
            type: string
      summary: Start monitoring Dofus window
      tags:
      - DofusCheck
  /dofus-check/stop:
    post:
      description: Stops the DofusCheckService which monitors the Dofus window state
      responses:
        "200":
          description: DofusCheck service stopped successfully
          schema:
            type: string
        "500":
          description: Error occurred while stopping the service
          schema:
            type: string
      summary: Stop monitoring Dofus window
      tags:
      - DofusCheck
  /focus/{keyword}:
    post:
      description: Met en avant une fenêtre qui contient un mot-clé spécifique dans
        son titre
      parameters:
      - description: Mot-clé pour identifier la fenêtre
        in: path
        name: keyword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Fenêtre mise en avant avec succès
          schema:
            type: string
        "500":
          description: Erreur lors de la mise en avant de la fenêtre
          schema:
            type: string
      summary: Met en avant une fenêtre spécifique
      tags:
      - Windows
  /shortcut/register/{key}/{windowName}:
    post:
      consumes:
      - application/json
      description: Registers a hotkey to focus on a window
      parameters:
      - description: Key to register
        in: path
        name: key
        required: true
        type: string
      - description: Name of the window to focus
        in: path
        name: windowName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a hotkey
      tags:
      - Shortcut
  /shortcut/unregister:
    delete:
      description: Unregisters a previously registered keyboard shortcut
      responses:
        "200":
          description: Raccourci désenregistré avec succès
          schema:
            type: string
        "500":
          description: Failed to unregister shortcut
          schema:
            type: string
      summary: Unregister an existing hotkey
      tags:
      - Shortcut
  /start-turn/start:
    get:
      consumes:
      - application/json
      description: Démarre le service pour écouter les événements d'une fenêtre spécifiée
        par son titre
      parameters:
      - description: Titre de la fenêtre à surveiller
        in: query
        name: windowTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Service démarré avec succès
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erreur si le service est déjà en cours ou si windowTitle est
            manquant
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Démarrer le service de détection d'événements pour une fenêtre spécifique
      tags:
      - StartTurn
  /start-turn/stop:
    get:
      description: Arrête le service d'écoute des événements sur une fenêtre
      produces:
      - application/json
      responses:
        "200":
          description: Service arrêté avec succès
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erreur si le service n'est pas en cours
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Arrêter le service de détection d'événements
      tags:
      - StartTurn
  /wheelclick/start:
    post:
      description: Listens for middle mouse clicks and triggers click simulation on
        Dofus windows.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Start middle mouse click detection
      tags:
      - WheelClick
  /wheelclick/stop:
    post:
      description: Stops the detection of middle mouse clicks.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Stop middle mouse click detection
      tags:
      - WheelClick
  /windows:
    get:
      description: Obtient la liste des fenêtres actuellement ouvertes sur le système
      produces:
      - application/json
      responses:
        "200":
          description: Liste des fenêtres ouvertes
          schema:
            items:
              type: string
            type: array
        "500":
          description: Erreur lors de la récupération des fenêtres
          schema:
            type: string
      summary: Retourne la liste des fenêtres ouvertes
      tags:
      - Windows
swagger: "2.0"
